### ISSUE TITLE
TrueSkill draw probability is not actually set to zero

### ISSUE THREAD

**Issue by tttppp** [ubitux/oraladder#3]
In https://github.com/ubitux/oraladder/blob/master/laddertools/ranking.py there is a line:
```self._env = trueskill.TrueSkill(draw_probability=0)```
However when I tried to reproduce the ratings using this locally then I got different values.  I think the issue is that the `draw_probability=0` is not having any effect because the rating update uses `trueskill` rather than `self._env`:
```r0, r1 = trueskill.rate_1vs1(winner_rating.internal, loser_rating.internal)```

If this is changed to the following then I think the ratings will be correct:
```r0, r1 = self._env.rate_1vs1(winner_rating.internal, loser_rating.internal)```

Alternatively, since the order of players seems to be fine*, and the incorrect ratings are known by the community, then another option would be to remove `draw_probability=0`.

As a comparison - without draw_probability=0:
```
Player          Rating  Games   Won
sup             3602    95      74
Kav             3547    200     175
Clockwork       3318    81      60
i like men      3313    40      38
Punsho          3110    79      47
morkel          2922    177     132
goat            2743    21      20
Mr Cloudy       2617    145     95
WhoCares        2558    161     92
Pinkthoth       2456    163     117
```
With draw_probability=0:
```
Player          Rating  Games   Won
sup             3545    95      74
Kav             3494    200     175
Clockwork       3272    81      60
i like men      3244    40      38
Punsho          3071    79      47
morkel          2885    177     132
goat            2690    21      20
Mr Cloudy       2597    145     95
WhoCares        2539    161     92
Pinkthoth       2442    163     117
```

\* Edit: The order of players is actually slightly different with the two settings - e.g.

Without draw_probability=0:
```
anjew   2031    28      20
Upps    2024    73      31
```

With draw_probability=0:
```
Upps    2027    73      31
anjew   2023    28      20
```

**Comment by ubitux** [comment]
Oh nicely spotted.

I will probably fix the rating:
- the impact is residual
- it is more correct (we can't have a draw)
- the gap of score between top players is smaller
